### ISSUE TITLE
Unable to use this library for IOS. Facing build errors in Xcode after following the guide.

### ISSUE THREAD

**Issue by shubham1164** [aksonov/react-native-xmpp#109]
I can use this library for Android with success but failed to use it in IOS. I have followed the official notes for installing this library and then install XMPPFramework pods and react-native-xmpp pods. But after that still I get one of the following errors:
1. Either I get core data model not found errors [issue#90](https://github.com/aksonov/react-native-xmpp/issues/90) [total 6 errors] or
2. XMPPframework.h not found error - According to me, this errors is due to the same name collision of the XMPPFramework.h file found in the XMPPFramework and RNXMPP folder or
3. I get errors in KissXML Framework or
4. Al last, if I mange to remove all the above errors, then I get the 'Linker failed error'.

Please help to provide the detailed documentation to use this library or if there is any alternative library for XMPP chat client that can be used in react-native for IOS. I have spent more than 2 weeks for searching the right solution for this.

**Comment by zek** [comment]
I have also XMPPFramework.h error

**Comment by shubham1164** [comment]
Hi Zek, it is better to shift to xmpp.js library. It is easy and simple. No fancy stuff

**Comment by FansPro** [comment]
@shubham1164  Hi. I have the same error.  Have u find the method to add it to ios or use other ?

**Comment by shubham1164** [comment]
@FansPro, I have migrated to xmpp.js
