### ISSUE TITLE
Feature request: Run towards self-signed cert.

### ISSUE THREAD

**Issue by Froelund** [aksonov/react-native-xmpp#12]
When developing it would be nice to point the application towards a local/development environment that has a self-signed certificate.

I'm considering implementing this behaviour with a method where you can define a list of trustedHosts, and then when trying to connect to one of those, the library will bypass the certificate checks.

What do you think @aksonov ?

I hesitate because that mechanism could really get someone in trouble. It definitely should not be used in production :)

**Comment by aksonov** [comment]
I'm fine with that, just please add docs not to use it in production :)
