### ISSUE TITLE
Cannot build after join/message room pull-request.

### ISSUE THREAD

**Issue by Froelund** [aksonov/react-native-xmpp#14]
As I see it, the feature isn't thought out as well. 
It would be better if the sendRoomMessage would accept a roomId, so you can manage the state in your application state, instead of in the native module.

<img width="744" alt="screen shot 2016-07-20 at 9 32 25 am" src="https://cloud.githubusercontent.com/assets/2089088/16977335/727db0c2-4e66-11e6-9828-4dadc467cce8.png">

**Comment by aksonov** [comment]
Got it, thanks

**Comment by Froelund** [comment]
Fixed in #15
