### ISSUE TITLE
Error when require('react-native-xmpp') on android project

### ISSUE THREAD

**Issue by fengarix** [aksonov/react-native-xmpp#21]
I already installed react-native-xmpp on my react native project by npm command `npm install --save react-native-xmpp` and link it with `rnpm link react-native-xmpp`.
When I want to require this module by typing this `var XMPP = require('react-native-xmpp');` to index.android.js I got an error: 

`undefined is not an object (evaluating 'RNXMPP.PLAIN')`

Why I get this error? and how to use react-native-xmpp on android project?

**Comment by Froelund** [comment]
@fengarix Which version of react-native?
I've seen this error when trying to use `rnpm link react-native-xmpp` on recent versions of react-native. 
You should check that the package is returned when getPackages is being called.
In your `MainApplication.java`

```
    @Override
    protected List<ReactPackage> getPackages() {
      return Arrays.<ReactPackage>asList(
          new MainReactPackage(),
          new RNXMPPPackage()
      );
    }
```

**Comment by fengarix** [comment]
Yeah solved!

I use version 0.30.0 of react native.
After adding `new RNXMPPPackage()` on `MainApplication.java`, I have to import the package by adding `import rnxmpp.RNXMPPPackage;` on `MainApplication.java`

Thanks a lot @Froelund

**Comment by shubham1164** [comment]
Hi, I am not able to find the MainApplication.java in the code. Please help.
