### ISSUE TITLE
Split connect and login

### ISSUE THREAD

**Issue by Froelund** [aksonov/react-native-xmpp#23]
In order to deliver better performance for the users, we should split up the connect part from the actual login.

With this split, we can connect to the server when the app starts up, and the swiftly authenticate the given credentials when the user submits auth form.

**Comment by Froelund** [comment]
What do you think about this @aksonov ?

**Comment by aksonov** [comment]
I'm ok if it will not break existing API.

**Comment by Froelund** [comment]
Hmm. Is guess we can manage without breaking the existing API.

**Comment by aksonov** [comment]
Great, then PR is welcome.
