### ISSUE TITLE
I want to add chat functionality in my react-native app.

### ISSUE THREAD

**Issue by devekoperiOS** [aksonov/react-native-xmpp#28]
Can any one please guide me about xmpp protocol. I mean I want to integrate chat functionality which is one to one and group chat like whatsapp in my react-native app. What server do I need to use and what client side library should I use to integrate chat module in react-native.

**Comment by Froelund** [comment]
I do think you should read up on how xmpp works if you want to implement a proper chat feature.

You could checkout the Demo application in this project. It connects to a free xmpp service called jabber.hot-chilli.net - I don't know much about that service in particular, but it might be enough to get you started.

I think [Ejabberd](https://www.ejabberd.im/) is the most used XMPP server, they have decent documentation on their website.
