### ISSUE TITLE
Android support

### ISSUE THREAD

**Issue by JonathanWi** [aksonov/react-native-xmpp#3]
Hey @aksonov, great implementation!
Any chance to see an android version anytime soon? It would be awesome to bridge [Smack](https://github.com/igniterealtime/Smack) the same way you did with iOS!

Have a great day,

Cheers

**Comment by aksonov** [comment]
Sorry, no plans yet...

**Comment by JonathanWi** [comment]
I know this isn't the right place to ask, but I can't find a way to DM you!
Could you get in touch with me at jonathan@pin.gg?

Thanks a lot

**Comment by chaitanyaK84** [comment]
Any updates on Android support please? If its not available right now, could you please let me know any alternate way to get React Native Xmpp working on Android?

**Comment by Froelund** [comment]
@aksonov This can be closed. Right?

**Comment by aksonov** [comment]
@Froelund i've just fixed demo for latest react native, could you check it on Android (now it is empty for android). I guess it should work just by rename index.ios.js into index.android.js? (RNRF is cross-platform now).

**Comment by Froelund** [comment]
@aksonov Sure 👍
