### ISSUE TITLE
undefined is not an object (evaluating 'RNXMPP.PLAIN')

### ISSUE THREAD

**Issue by llgoer** [aksonov/react-native-xmpp#4]
after install ios debug application show error like:
undefined is not an object (evaluating 'RNXMPP.PLAIN')

**Comment by llgoer** [comment]
I know,*_libresolv_ is not add to project..

**Comment by shubham1164** [comment]
I am getting the same error in Android. I am using the react-native: 0.56.0.

Error: undefined is not an object (evaluating 'RNXMPP.PLAIN')

I have confirmed that linking is done. but still the issue is not resolved. Please help
