### ISSUE TITLE
how define server to xmpp ?

### ISSUE THREAD

**Issue by a11231g** [aksonov/react-native-xmpp#50]
my jid is something line user@siteName.com
and server is something like ws://test.siteNAme.com:5280/websocket

i didnt find any config to set the server address , pls help

**Comment by Froelund** [comment]
You can do that as param 4 in the connect method:
https://github.com/aksonov/react-native-xmpp/blob/master/index.js#L104
```
RNXMPP.connect("user@siteName.com", "pw", RNXMPP.SCRAMSHA1, "test.siteNAme.com", 5222);
```
However I do believe that this library does not support Websockets.

**Comment by a11231g** [comment]
thanks it worked , 
import { NativeModules } from 'react-native'
NativeModules.RNXMPP.connect("user@siteName.com", "pw", RNXMPP.SCRAMSHA1, "test.siteNAme.com", 5222)

i was trying to set host on XMPP.connect("user@siteName.com", "pw", RNXMPP.SCRAMSHA1, "test.siteNAme.com", 5222)
which takes just 2 parameters,
thanks a lot
