### ISSUE TITLE
java.net.ConnectException : bad file descriptor

### ISSUE THREAD

**Issue by anishu23** [aksonov/react-native-xmpp#60]
When I try to connect to my XMPP server, it gives the following error

`react-native-xmpp: Error: The following addresses failed: 'mydomain.com:5222' failed because java.net.ConnectException: Bad file descriptor`
where mydomain.com is dummy in this comment

But when I connect from Pidgin to the same server and everything works fine.
What might the problem?

**Comment by anishu23** [comment]
Found the problem. I had my name servers set to cloudflare and it does not allow traffic on the port 5222.

Ref: https://support.cloudflare.com/hc/en-us/articles/200169156-Which-ports-will-Cloudflare-work-with-

**Comment by anishu23** [comment]
Is there any way that I just send the request on a url and not like "domainname.com:5222"  and just "domainame.com"? where i have proxyed the port to the domain name. P.S. Don't know if I am using the right terms here. Please feel free to correct me.

**Comment by aksonov** [comment]
Sorry, there is no such way, you must specify the port number
