### ISSUE TITLE
Login error: The operation couldn’t be completed. (kCFStreamErrorDomainSSL error -9825.)

### ISSUE THREAD

**Issue by boowee** [aksonov/react-native-xmpp#62]
When I try to connect to my XMPP server, it gives the error:
`The operation couldn’t be completed. (kCFStreamErrorDomainSSL error -9825.)`

What might the problem? Thanks

**Comment by aksonov** [comment]
It is SSL error between your client and your server.

**Comment by waterstar** [comment]
May I know if we can accept self-signed certificate?

**Comment by piyush2cloud** [comment]
@boowee @aksonov @waterstar 
I am also facing same issue while making tls connection. Can someone help me solve it.
