### ISSUE TITLE
Android build failure  :react-native-xmpp:compileReleaseJavaWithJavac

### ISSUE THREAD

**Issue by ghost** [aksonov/react-native-xmpp#63]
Hey, I installed react-native-xmpp as described and linked Binarys with 'rnpm link react-native-xmpp'
and extra linking for ios in XCode -> Ios is working.

Building the Android Version I get this error: 

```
:react-native-xmpp:compileReleaseJavaWithJavac
:react-native-xmpp:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
...APP/node_modules/react-native-xmpp/android/src/main/java/rnxmpp/RNXMPPPackage.java:28: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: ...APP/node_modules/react-native-xmpp/android/src/main/java/rnxmpp/service/XmppServiceSmackImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-xmpp:compileReleaseJavaWithJavac FAILED
```

Node Version7.7.4 , installed everything with yarn.
Any idea how to fix this? Did I miss a linking Step?
Thanks alot!

Edit: I get this WARNUNG, same thing was fixed and closed in #55 

WARNING: WARNING: Dependency xpp3:xpp3:1.1.4c is ignored for debug as it may be conflicting with the internal version provided by Android.
         In case of problem, please repackage it with jarjar to change the class packages

**Comment by ghost** [comment]
Linking wasnt correct and the Package is deprecated (jsModules aren't required anymore in the NativeModules Interface)
Check my Fork or wait for the Pullrequest.

**Comment by saivamsid** [comment]
Hey, I am trying to run the demo app, its showing the following error ,please help.

`C:\android\react-native-xmpp\XmppDemo\node_modules\react-native-xmpp\android\src\main\java\rnxmpp\RNXMPPPackage.java:18: error: RNXMPPPackage is not abstract and does not override abstract method createJSModules() in ReactPackage
public class RNXMPPPackage implements ReactPackage{`

**Comment by akshgods** [comment]
@saivamsid  same issue is here

**Comment by hsrashmi** [comment]
I see the issue being closed. But whats the solution? I'm also facing same issue as @saivamsid

**Comment by haythamforever** [comment]
anybody solved that ?
