### ISSUE TITLE
Android Require Package Build Failure

### ISSUE THREAD

**Issue by trevorwhealy** [aksonov/react-native-xmpp#69]
`import XMPP from "react-native-xmpp"`

Prevents a successful build with the following errors:

```js
:react-native-xmpp:compileReleaseJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
/Users/trevorhealy/Programming/Applications/abc/abc/node_modules/react-native-xmpp/android/src/main/java/rnxmpp/RNXMPPPackage.java:28: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /Users/trevorhealy/Programming/Applications/abc/abc/node_modules/react-native-xmpp/android/src/main/java/rnxmpp/service/XmppServiceSmackImpl.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
:react-native-xmpp:compileReleaseJavaWithJavac FAILED
```

`FAILURE: Build failed with an exception.`

* What went wrong:
Execution failed for task ':react-native-xmpp:compileReleaseJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

Here is my React Native Version:
```XML
react-native --v
react-native-cli: 2.0.1
react-native: 0.48.4
```

**Comment by johakr** [comment]
Same issue here. Any plans on fixing this?

**Comment by johakr** [comment]
Okay, nvm. There are already 2 merge requests open for over a month targeting this issue. Looks like this library is unfortunately kinda abandoned. As a workaround one can downgrade to react-native@0.46 or apply the fix from the merge request manually. @aksonov any plans on continue maintaining this library?

**Comment by aksonov** [comment]
I was on vacation, please check now. Android support was done by other developer, so I can say that iOS version is working fine in our production app (we don't have Android app at this moment)

**Comment by johakr** [comment]
Works great now. Thank you! 👍 Probably worth to be published as a new version asap.

**Comment by xcrafter** [comment]
merged with master?

**Comment by ahmadsyamim** [comment]
> deleted
my gradle version error

**Comment by aksonov** [comment]
Please check latest 0.6.0
