### ISSUE TITLE
retrieve chat history

### ISSUE THREAD

**Issue by faysal515** [aksonov/react-native-xmpp#70]
How do I retrieve past chat history with other users(JID)?

**Comment by aksonov** [comment]
You may add any custom logic by sending proper IQ stanzas to the xmpp server.
Use https://xmpp.org/extensions/xep-0136.html if your server supports it.

**Comment by faysal515** [comment]
I tried sending custom stanza to the server and it's getting appropriate results in IOS. however on android, it's throwing `E/AbstractXMPPConnection: Exception in async packet listener`. here's my stanza 
```xml
<iq type='get' id='get_archive_user1'>
  <query xmlns='urn:xmpp:mam:tmp'>
       <with>one-id@host</with>
        <set xmlns='http://jabber.org/protocol/rsm'>
            <max>3</max>
             <before/>
        </set>
   </query>
</iq>
```

![screen shot 2018-01-23 at 11 21 19 am](https://user-images.githubusercontent.com/10289348/35259356-926ae586-002f-11e8-8c5c-0b44fabad3d1.png)

I turned on the debugger and saw that my server is sending me back 3 message IQ and one mam iq. here's the structure of the mam IQ

```xml
<iq xml:lang='en' to='myjid@domain/mobile' from=myjid@domain' type='result' id='get_archive_user1'>
	<query
		xmlns='urn:xmpp:mam:tmp'>
		<set
			xmlns='http://jabber.org/protocol/rsm'>
			<count>13</count>
			<first>1516626929629802</first>
			<last>1516627954985473</last>
		</set>
	</query>
</iq>
```

But in the `XmppServiceSmackImpl` file, this `iq` is being parsed as `UnparsedIQ` class which eventually throws error and data is not sent in the JS

**Comment by CocktailZY** [comment]
Have you solved this problem?

**Comment by faysal515** [comment]
@CocktailZY yes, but the solution still have few minor issues. I'm planning to create a PR. Though not sure when I will be able to get some time to work on this
