### ISSUE TITLE
making it usable with RN Version 0.42.0

### ISSUE THREAD

**Issue by vigasdeep** [aksonov/react-native-xmpp#72]
When I tried it says:
Undefined is not an object (evaluating 'RNXMPP.PLAIN')

Any hint will be helpful.
Thanks

**Comment by kasran15** [comment]
Happened to me as well when i upgraded to RN 0.50.3

**Comment by vigasdeep** [comment]
@kasran15 thanks for replying. Did you get it working with any previous versions greater than 0.41.0?

**Comment by aksonov** [comment]
@Froelund Could you check? I have this issue only for Android and RN0.50.3

**Comment by aksonov** [comment]
@Froelund never mind, it works after proper linking.

@vigasdeep You have to link this module using `react-native link react-native-xmpp`

**Comment by Kunal8195** [comment]
I linked it with` rnpm link react-native-xmpp `still getting the same error. help me, please.

**Comment by Kunal8195** [comment]
Found the solution here in one of the closed issues. https://github.com/aksonov/react-native-xmpp/issues/21

**Comment by kasran15** [comment]
Using this command is not fixing it for me
react-native link react-native-xmpp

However, when i use
rnpm link react-native-xmpp, it links it properly but The BUILD fails because of missing XMPPFramework

**Comment by faheemahmad** [comment]
I am getting this same issue on xcode 9.4 ,my RN 0.55.4 , and i am new on react native  , did not work your solution for  me

**Comment by shubham1164** [comment]
I am getting the same error in Android. I am using the react-native: 0.56.0.

**Error**: undefined is not an object (evaluating 'RNXMPP.PLAIN')

I have confirmed that linking is done. but still the issue is not resolved. Please help
