### ISSUE TITLE
createJsModule function is showing on installing via npm

### ISSUE THREAD

**Issue by xcrafter** [aksonov/react-native-xmpp#78]
as createJsModule function is not showing in the [RNXMPPPackage.java](https://github.com/aksonov/react-native-xmpp/blob/master/android/src/main/java/rnxmpp/RNXMPPPackage.java)

but when installing the package@latest version via npm showing the function. 

I am using rn version 0.48.0

**Comment by aksonov** [comment]
Please check latest 0.6.0 from npm
