### ISSUE TITLE
IOS rnpm link or react-native link are not working

### ISSUE THREAD

**Issue by nimabk82** [aksonov/react-native-xmpp#83]
I run the project successfully in android but in IOS when I linked (by rnpm or react-native link)   XmppDemo.xcodeprog added to project , even after adding RNXMPP.xcodeprog manually and adding those files in binary link the build is failed and all the folders in XMPP  framework (like vendor, core , ... ) are empty.

react-native : 0.49.5
xmpp : 0.6.0

**Comment by ghitatomy** [comment]
@aksonov Please commit the Podfile from ios directory. If you are not using pods in project then podspecs are useless! And will be a source of errors.

**Comment by rptwsthi** [comment]
@nimamyscreen Did you find any solution for this, I ma facing same issue in my application.

**Comment by aksonov** [comment]
Please use CocoaPods, I just updated readme.
