### ISSUE TITLE
Error Domain=NSCocoaErrorDomain Code=260

### ISSUE THREAD

**Issue by imrankhanjoya** [aksonov/react-native-xmpp#85]
Could not determine generated file paths for Core Data code generation: Error Domain=NSCocoaErrorDomain Code=260 "No current version for model at path /usr/local/lib/node_modules/react-native-xmpp/XMPPFramework/Extensions/XEP-0045/CoreDataStorage/XMPPRoom.xcdatamodeld:" UserInfo={NSFilePath=/usr/local/lib/node_modules/react-native-xmpp/XMPPFramework/Extensions/XEP-0045/CoreDataStorage/XMPPRoom.xcdatamodeld, NSLocalizedDescription=No current version for model at path /usr/local/lib/node_modules/react-native-xmpp/XMPPFramework/Extensions/XEP-0045/CoreDataStorage/XMPPRoom.xcdatamodeld:}

getting this error ... Please let me know how to debug this

**Comment by aksonov** [comment]
Please use CocoaPods, I just updated readme.
