### ISSUE TITLE
getting Error like serverlessDemo when we are archiving to project

### ISSUE THREAD

**Issue by lavarajallu** [aksonov/react-native-xmpp#92]
Xcode:9.2,
react-native:0.50
Showing Recent Issues
ld: '/Users/xxxxxx/Documents/TodayClone/xxxxxxxx/node_modules/react-native-xmpp/XMPPFramework/Vendor/libidn/libidn.a(stringprep.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64

stille

**Comment by aksonov** [comment]
You must disable bitcode setting
