### ISSUE TITLE
Undifined is not an object (evaluvating RNXMPP.PLAIN)

### ISSUE THREAD

**Issue by AAGSICON** [aksonov/react-native-xmpp#94]
Undifined is not an object (evaluvating RNXMPP.PLAIN)

how can i solve this issue
i got this issue in ios
but in android it work fine

**Comment by Mian007** [comment]
SAME ERROR

**Comment by aksonov** [comment]
Please use CocoaPods for the installation, I just updated readme.

**Comment by vishnusurabhirao** [comment]
@aksonov I am new to react. Can you please guide me in right path.
I am getting the bellow error while installing *pod*
 
<img width="1031" alt="screen shot 2018-07-03 at 1 25 05 pm" src="https://user-images.githubusercontent.com/26630831/42206383-9069b7ee-7ec4-11e8-9c3f-57c23ed29f3e.png">
